#!/usr/bin/env bash

#
# Homebrew
#

echo "Installing Homebrew, a good OS X package manager ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

#
# Utilities
#

echo "Installing ag, a good way to search through files ..."
  brew install the_silver_searcher

echo "Installing neovim, a great text editor ..."
  brew install neovim

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux
  brew install reattach-to-user-namespace

echo "Installing ctags, useful for vim ..."
  brew install ctags

#
# Ruby
#

echo "Installing chruby, for managing rubies"
  brew install chruby

echo "Installing ruby-install, for building rubies"
  brew install ruby-install

echo "Installing lastest stable Ruby release and making it the default Ruby ..."
  ruby-install ruby
  echo "
# chruby config
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
" >> ~/.zshrc
  source ~/.zshrc
