#!/usr/bin/env bash

#
# SSH keys configuration
#

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

#
# Homebrew
#

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#
# Utilities
#

echo "Installing ag, a good way to search through files ..."
  brew install the_silver_searcher

echo "Installing neovim, the best text editor ..."
  brew install neovim

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux
  brew install reattach-to-user-namespace

echo "Installing ctags, useful for vim ..."
  brew install ctags

echo "Installing GraphicsMagick, good for cropping and re-sizing images ..."
  brew install graphicsmagick

#
# Databases
#

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres

echo "Installing MySQL, another good open source relational database ..."
  brew install mysql

echo "Installing Redis, a key/value database ..."
  brew install redis

#
# Ruby
#

echo "Installing chruby, for managing rubies"
  brew install chruby

echo "Installing ruby-install, for building rubies"
  brew install ruby-install

echo "Installing lastest stable Ruby release and making it the default Ruby ..."
  ruby-install ruby stable
  echo "
# chruby config
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby stable
" >> ~/.zshrc
  source ~/.zshrc

echo "WARNING: Remember to setup postgres, mysql and redis!"
